# SPDX-License-Identifier: MIT
"""Sheet rows to a Markdown table, and the comparison against the file already there."""

from __future__ import annotations

import difflib
from collections.abc import Sequence
from dataclasses import dataclass

from bac_common.errors import BacError

__all__ = ["Rendered", "escape_cell", "render", "diff_stats", "GENERATED_NOTE"]

GENERATED_NOTE = "<!-- Generated by bac-update-content-plan from {url} – edit the sheet, not this file. -->"


@dataclass(frozen=True, slots=True)
class Rendered:
    text: str
    columns: int
    rows_total: int
    """Data rows the sheet returned (the header not counted, empty rows not counted)."""
    rows_kept: int
    """Rows written after the status filter."""
    filtered: bool
    """Whether the status column was found and the filter applied."""


def escape_cell(value: str) -> str:
    """Make a cell safe inside a Markdown table row: pipes escaped, line breaks flattened."""
    text = value.replace("\r\n", "\n").replace("\r", "\n")
    text = " ".join(part.strip() for part in text.split("\n") if part.strip())
    return text.replace("|", "\\|")


def render(values: Sequence[Sequence[str]], *, title: str, status_column: str, sheet_url: str) -> Rendered:
    """One H1, a generated-file note, and the table.

    The first row is the header. Rows that are empty in every cell are
    dropped; when ``status_column`` names a header cell, rows with an empty
    value there are dropped too (the sheet's drafts and placeholders). Short
    rows are padded to the header's width, longer ones extend it.
    """
    if not values or not any(cell.strip() for cell in values[0]):
        raise BacError("The sheet range returned no header row.", "Check [sheet] range in the config.")
    width = max(len(row) for row in values)
    padded = [list(row) + [""] * (width - len(row)) for row in values]
    header = [escape_cell(cell) for cell in padded[0]]
    body = [row for row in padded[1:] if any(cell.strip() for cell in row)]
    total = len(body)

    filtered = False
    if status_column:
        try:
            index = [cell.strip() for cell in padded[0]].index(status_column)
        except ValueError:
            index = -1
        if index >= 0:
            body = [row for row in body if row[index].strip()]
            filtered = True

    lines = [
        GENERATED_NOTE.format(url=sheet_url),
        f"# {title}",
        "",
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(["---"] * width) + " |",
    ]
    lines.extend("| " + " | ".join(escape_cell(cell) for cell in row) + " |" for row in body)
    return Rendered("\n".join(lines) + "\n", width, total, len(body), filtered)


def diff_stats(old: str | None, new: str) -> tuple[int, int]:
    """``(added, removed)`` line counts between the file on disk and the rendering. ``None`` = no file yet."""
    if old is None:
        return new.count("\n"), 0
    added = removed = 0
    for line in difflib.unified_diff(old.splitlines(), new.splitlines(), lineterm="", n=0):
        if line.startswith("+") and not line.startswith("+++"):
            added += 1
        elif line.startswith("-") and not line.startswith("---"):
            removed += 1
    return added, removed
