# SPDX-License-Identifier: MIT
from __future__ import annotations

import pytest
from bac_update_content_plan.render import diff_stats, escape_cell, render
from bac_update_content_plan.settings import DEFAULTS, config_text, load_settings
from contentplan_testkit import SHEET_ID, VALUES

from bac_common.errors import BacError, ConfigError

URL = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/edit"


def test_escape_cell():
    assert escape_cell("a | b") == "a \\| b"
    assert escape_cell("one\r\n two \n\nthree ") == "one two three"
    assert escape_cell("  ") == ""


def test_render_filters_pads_and_escapes():
    out = render(VALUES, title="Content Plan", status_column="Status", sheet_url=URL)
    lines = out.text.splitlines()
    assert lines[0].startswith("<!-- Generated by bac-update-content-plan from https://docs.google.com/")
    assert lines[1] == "# Content Plan"
    assert lines[3] == "| Title | Channel | Status | Notes |"
    assert lines[4] == "| --- | --- | --- | --- |"
    assert lines[5] == "| Why a 1U \\| not a 3U | YouTube | draft | line one line two |"
    assert lines[6] == "| EPS walkthrough | YouTube | published |  |"
    assert len(lines) == 7
    assert out.text.endswith("|\n")
    assert (out.columns, out.rows_total, out.rows_kept, out.filtered) == (4, 3, 2, True)


def test_render_without_status_column_keeps_rows():
    out = render(VALUES, title="T", status_column="Stage", sheet_url=URL)
    assert out.rows_kept == 3
    assert out.filtered is False
    off = render(VALUES, title="T", status_column="", sheet_url=URL)
    assert off.rows_kept == 3
    assert off.filtered is False


def test_render_longer_body_row_extends_the_table():
    values = [["A", "B"], ["1", "2", "3"]]
    out = render(values, title="T", status_column="", sheet_url=URL)
    assert "| A | B |  |" in out.text
    assert "| 1 | 2 | 3 |" in out.text
    assert out.columns == 3


@pytest.mark.parametrize("values", [[], [[]], [["", ""]]])
def test_render_without_header_fails(values):
    with pytest.raises(BacError, match="no header"):
        render(values, title="T", status_column="", sheet_url=URL)


def test_diff_stats():
    assert diff_stats(None, "a\nb\n") == (2, 0)
    assert diff_stats("a\nb\n", "a\nb\n") == (0, 0)
    assert diff_stats("a\nb\nc\n", "a\nx\n") == (1, 2)


def test_load_settings_defaults_and_url_id(tmp_path):
    config = {
        "sheet": {"id": f"{URL}?gid=0"},
        "output": {"repo": str(tmp_path / "docs")},
    }
    s = load_settings(config)
    assert s.sheet_id == SHEET_ID
    assert s.a1_range == DEFAULTS["range"]
    assert s.title == DEFAULTS["title"]
    assert s.status_column == "Status"
    assert s.repo == (tmp_path / "docs").resolve()
    assert s.file == DEFAULTS["file"]
    assert s.target == s.repo / "content/content-plan.md"
    assert (s.branch, s.remote, s.credentials_file) == ("main", "origin", "")
    assert s.sheet_url == URL


def test_load_settings_status_column_off_and_errors(tmp_path):
    base = {"sheet": {"id": SHEET_ID, "status_column": ""}, "output": {"repo": "~/docs"}}
    assert load_settings(base).status_column == ""
    with pytest.raises(ConfigError, match="not set up"):
        load_settings({})
    with pytest.raises(ConfigError, match="not set up: missing output.repo"):
        load_settings({"sheet": {"id": SHEET_ID}})
    with pytest.raises(ConfigError, match="relative path"):
        load_settings({"sheet": {"id": SHEET_ID}, "output": {"repo": "~/d", "file": "/etc/plan.md"}})
    with pytest.raises(ConfigError, match="relative path"):
        load_settings({"sheet": {"id": SHEET_ID}, "output": {"repo": "~/d", "file": "../plan.md"}})
    with pytest.raises(ConfigError, match="must be a table"):
        load_settings({"sheet": {"id": SHEET_ID}, "output": {"repo": "~/d"}, "credentials": "x"})
    with pytest.raises(ConfigError, match="Not a Google Sheets id"):
        load_settings({"sheet": {"id": "content plan"}, "output": {"repo": "~/d"}})


def test_config_text_round_trips():
    import tomllib

    text = config_text(SHEET_ID, "~/bac/bac-docs", "content/content-plan.md", "main")
    data = tomllib.loads(text)
    s = load_settings(data)
    assert s.sheet_id == SHEET_ID
    assert s.status_column == "Status"
    assert s.file == "content/content-plan.md"
    assert "BAC_GCP_CREDENTIALS" in text
